<a href="https://colab.research.google.com/github/Wendyacero/Actividades-Programaci-n-Anal-tica/blob/main/ACTIVIDAD_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import pandas as pd
import matplotlib as plt
import scipy as sp

In [6]:
url = 'https://raw.githubusercontent.com/camilorobledo0-creator/Actividad-5/refs/heads/main/Propuestas%20Investigacion-1.csv'
dataini = pd.read_csv(url, sep=';')

In [7]:
data = dataini.copy()
data.shape

(305, 36)

In [8]:
data.columns

Index(['AÑO', 'TIPO', 'ESTADO', 'No. CONVOCATORIA', 'NOMBRE CONVOCATORIA',
       'ENTIDAD', 'ROL UDFJC', 'ALIADO', 'PROGRAMA', 'MESES',
       'GRUPOS DE INVESTIGACIÓN', 'VALOR PROYECTO',
       'RECURSOS EN EFECTIVO FINANCIADO A UDFJC', 'VALOR PROYECTO EFECTIVO',
       'VALOR PROYECTO ESPECIE', 'SOLICITADO A ENTIDAD', 'UDFJC EFECTIVO',
       'UDFJC ESPECIE', 'SOLICITADO ALIADO 1\nEFECTIVO',
       'SOLICITADO ALIADO 1\nESPECIE', 'SOLICITADO ALIADO 2\nEFECTIVO',
       'SOLICITADO ALIADO 2\nESPECIE', 'SOLICITADO ALIADO 3\nEFECTIVO',
       'SOLICITADO ALIADO 3\nESPECIE', 'SOLICITADO ALIADO 4\nEFECTIVO',
       'SOLICITADO ALIADO 4\nESPECIE', 'RESULTADOS ESPERADOS',
       'PRODUCTOS ESPERADOS', '% Aportes Colciencias', '% Aportes UDFJC',
       '% Aportes UDFJC Efectivo', '% Aportes UDFJC Especie',
       '% Aportes Aliado 1', '% Aportes Aliado 2', '% Aportes Aliado 3',
       '% Aportes Aliado 4'],
      dtype='object')

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 305 entries, 0 to 304
Data columns (total 36 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   AÑO                                      305 non-null    int64
 1   TIPO                                     305 non-null    object
 2   ESTADO                                   305 non-null    object
 3   No. CONVOCATORIA                         240 non-null    object
 4   NOMBRE CONVOCATORIA                      252 non-null    object
 5   ENTIDAD                                  302 non-null    object
 6   ROL UDFJC                                304 non-null    object
 7   ALIADO                                   240 non-null    object
 8   PROGRAMA                                 15 non-null     object
 9   MESES                                    305 non-null    object
 10  GRUPOS DE INVESTIGACIÓN                  231 non-null    object
 11  VALOR PROYECTO                           305 non-null    object
 12  RECURSOS EN EFECTIVO FINANCIADO A UDFJC  305 non-null    object
 13  VALOR PROYECTO EFECTIVO                  305 non-null    object
 14  VALOR PROYECTO ESPECIE                   305 non-null    object
 15  SOLICITADO A ENTIDAD                     305 non-null    object
 16  UDFJC EFECTIVO                           305 non-null    object
 17  UDFJC ESPECIE                            305 non-null    object
 18  SOLICITADO ALIADO 1
EFECTIVO             305 non-null    object
 19  SOLICITADO ALIADO 1
ESPECIE              305 non-null    object
 20  SOLICITADO ALIADO 2
EFECTIVO             305 non-null    object
 21  SOLICITADO ALIADO 2
ESPECIE              305 non-null    object
 22  SOLICITADO ALIADO 3
EFECTIVO             305 non-null    object
 23  SOLICITADO ALIADO 3
ESPECIE              305 non-null    object
 24  SOLICITADO ALIADO 4
EFECTIVO             305 non-null    object
 25  SOLICITADO ALIADO 4
ESPECIE              305 non-null    object
 26  RESULTADOS ESPERADOS                     305 non-null    object
 27  PRODUCTOS ESPERADOS                      305 non-null    object
 28  % Aportes Colciencias                    305 non-null    object
 29  % Aportes UDFJC                          305 non-null    object
 30  % Aportes UDFJC Efectivo                 305 non-null    object
 31  % Aportes UDFJC Especie                  305 non-null    object
 32  % Aportes Aliado 1                       305 non-null    object
 33  % Aportes Aliado 2                       305 non-null    object
 34  % Aportes Aliado 3                       305 non-null    object
 35  % Aportes Aliado 4                       305 non-null    object
dtypes: int64(1), object(35)
memory usage: 85.9+ KB

In [19]:
data.shape
data.info()
data.isnull().sum()
data['ESTADO'].value_counts()
data.nunique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 305 entries, 0 to 304
Data columns (total 36 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   AÑO                                      305 non-null    int64
 1   TIPO                                     305 non-null    object
 2   ESTADO                                   305 non-null    object
 3   No. CONVOCATORIA                         240 non-null    object
 4   NOMBRE CONVOCATORIA                      252 non-null    object
 5   ENTIDAD                                  302 non-null    object
 6   ROL UDFJC                                304 non-null    object
 7   ALIADO                                   240 non-null    object
 8   PROGRAMA                                 15 non-null     object
 9   MESES                                    305 non-null    object
 10  GRUPOS DE INVESTIGACIÓN                  231 non-null    object
 11  VALOR PROYECTO                           305 non-null    object
 12  RECURSOS EN EFECTIVO FINANCIADO A UDFJC  305 non-null    object
 13  VALOR PROYECTO EFECTIVO                  305 non-null    object
 14  VALOR PROYECTO ESPECIE                   305 non-null    object
 15  SOLICITADO A ENTIDAD                     305 non-null    object
 16  UDFJC EFECTIVO                           305 non-null    object
 17  UDFJC ESPECIE                            305 non-null    object
 18  SOLICITADO ALIADO 1
EFECTIVO             305 non-null    object
 19  SOLICITADO ALIADO 1
ESPECIE              305 non-null    object
 20  SOLICITADO ALIADO 2
EFECTIVO             305 non-null    object
 21  SOLICITADO ALIADO 2
ESPECIE              305 non-null    object
 22  SOLICITADO ALIADO 3
EFECTIVO             305 non-null    object
 23  SOLICITADO ALIADO 3
ESPECIE              305 non-null    object
 24  SOLICITADO ALIADO 4
EFECTIVO             305 non-null    object
 25  SOLICITADO ALIADO 4
ESPECIE              305 non-null    object
 26  RESULTADOS ESPERADOS                     305 non-null    object
 27  PRODUCTOS ESPERADOS                      305 non-null    object
 28  % Aportes Colciencias                    305 non-null    object
 29  % Aportes UDFJC                          305 non-null    object
 30  % Aportes UDFJC Efectivo                 305 non-null    object
 31  % Aportes UDFJC Especie                  305 non-null    object
 32  % Aportes Aliado 1                       305 non-null    object
 33  % Aportes Aliado 2                       305 non-null    object
 34  % Aportes Aliado 3                       305 non-null    object
 35  % Aportes Aliado 4                       305 non-null    object
dtypes: int64(1), object(35)
memory usage: 85.9+ KB

AÑO                                          9
TIPO                                         4
ESTADO                                       6
No. CONVOCATORIA                            85
NOMBRE CONVOCATORIA                        110
ENTIDAD                                     51
ROL UDFJC                                    6
ALIADO                                     225
PROGRAMA                                    13
MESES                                       32
GRUPOS DE INVESTIGACIÓN                    179
VALOR PROYECTO                             265
RECURSOS EN EFECTIVO FINANCIADO A UDFJC     62
VALOR PROYECTO EFECTIVO                    240
VALOR PROYECTO ESPECIE                     225
SOLICITADO A ENTIDAD                       221
UDFJC EFECTIVO                              48
UDFJC ESPECIE                              198
SOLICITADO ALIADO 1\nEFECTIVO               49
SOLICITADO ALIADO 1\nESPECIE               151
SOLICITADO ALIADO 2\nEFECTIVO               15
SOLICITADO ALIADO 2\nESPECIE                86
SOLICITADO ALIADO 3\nEFECTIVO                8
SOLICITADO ALIADO 3\nESPECIE                65
SOLICITADO ALIADO 4\nEFECTIVO                4
SOLICITADO ALIADO 4\nESPECIE                46
RESULTADOS ESPERADOS                       248
PRODUCTOS ESPERADOS                        251
% Aportes Colciencias                      205
% Aportes UDFJC                            214
% Aportes UDFJC Efectivo                    53
% Aportes UDFJC Especie                     53
% Aportes Aliado 1                         158
% Aportes Aliado 2                          90
% Aportes Aliado 3                          60
% Aportes Aliado 4                          42
dtype: int64

In [22]:
print(data['PROGRAMA'].value_counts())

PROGRAMA
Pertenence a un programa                                                                                                                                                                                                                  2
Linea 3 Alcance 2                                                                                                                                                                                                                         2
CAPACIDADES COMUNITARIAS EN ZONAS RURALES DE POSACUERDO: OPORTUNIDADES PARA DISMINUIR DESIGUALDADES                                                                                                                                       1
NANOMATERIALES Y DISPOSITIVOS OPTOELECTRÓNICOS                                                                                                                                                                                            1
PROGRAMA DE ENTRENAMIENTO COGNITIVO BASADO EN LA PRÁCTICA DEL AJEDREZ PARA ESTIMULAR LAS FUNCIONES EJECUTIVAS IMPLICADAS EN EL PENSAMIENTO LÓGICO MATEMÁTICO. DIRIGIDO A ESTUDIANTES DEL PRIMER CICLO DE EDUCACIÓN BÁSICA                 1
Configuración de categorías mediante procesos de innovación para la inclusión y el reconocimiento de la diversidad y diferencia cultural en la educación científica: Estudios de caso en los niveles educativos Básico y Universitario    1
Desarrollo y validación de un prototipo de sensor electrofisiológico para medir estrés en plantas.                                                                                                                                        1
106072 - Centro de planeación de microrredes inteligentes                                                                                                                                                                                 1
Programa de Investigación en Tecnologías Emergentes para Microrredes Eléctricas Inteligentes con Alta Penetración\nde Energías Renovables                                                                                                 1
Linea 2 Alcance 1                                                                                                                                                                                                                         1
Linea 3 Alcance 1                                                                                                                                                                                                                         1
Linea 4 Alcance 1                                                                                                                                                                                                                         1
OPTIMIZACIÓN DEL DIAGNÓSTICO Y MANEJO DE LA DIABETES MEDIANTE MODELOS AVANZADOS DE DATOS Y BIOMARCADORES DIGITALES EN MUNICIPIOS DE GUACARÍ - VALLE DEL CAUCA Y HONDA - TOLIMA                                                            1
Name: count, dtype: int64

In [25]:
data['ESTADO'].value_counts()

ESTADO
No Avalada          181
Contrato firmado     43
Desistio             27
Seleccionada         23
Avalada              17
En tramite           14
Name: count, dtype: int64

In [27]:
data['ENTIDAD'].value_counts()

ENTIDAD
MinCiencias                                                                                             214
MinAmbiente (SGR)                                                                                        14
SUE DISTRITO CAPITAL                                                                                     11
ATENEA                                                                                                    5
Universidad Pedagógica Nacional - UPN                                                                     4
UDFJC                                                                                                     3
Agencia Nacional del Espectro - ANE                                                                       3
Embajada de Francia en Colombia                                                                           3
ICFES                                                                                                     2
MinCultura                                                                                                2
Alcaldía de Fontibón                                                                                      1
UNIMINUTO                                                                                                 1
Secretaria de Gobierno Bogotá                                                                             1
IDEP                                                                                                      1
Fundación para la Promoción de la Investigación y la Tecnología del Banco de la República                 1
Fuerza Aérea Colombiana FAC                                                                               1
Universidad de Sucre                                                                                      1
Secretaria de Educación Distrital - Dirección de formación de docentes e Innovaciones Pedagógicas         1
EAN - ICC                                                                                                 1
Corporación Universitaria Iberoamericana                                                                  1
Universidad de América                                                                                    1
SUE Distrito Capital                                                                                      1
International Atomic  Energy Agency - IAEA                                                                1
Unidad Administrativa Especial de Catastro Distrital - IDECA                                              1
ICETEX                                                                                                    1
Universidad Pontificia Javeriana - PUJ                                                                    1
Secretaria Distrital de Desarrollo Económico - SDDE                                                       1
Instituto de Investigación de Recursos Biológicos Alexander von Humboldt                                  1
Universidad Antonio Nariño - UAN                                                                          1
Universidad del Bosque                                                                                    1
Embajada de República Checa en Bogotá                                                                     1
Universidad Militar Nueva Granada                                                                         1
Auditoria General De La Republica                                                                         1
BEL STAR S.A.                                                                                             1
CODENSA S.A.- E.S.P\nEMGESA S.A. - E.S.P                                                                  1
Programa BMBF Alemania                                                                                    1
Programa Regional Stic-Amsud Francia 2022                                                                 1
Programa ECOSNORD Francia                                                                                 1
Junta de Andalucía - España                                                                               1
Departamento de Medio Ambiente, Alimentación y Asuntos Rurales (Defra) del Gobierno del Reino Unido.      1
FAPEMIG                                                                                                   1
Consejo Superior Universitario CentroAmericano (CSUCA)                                                    1
Sussex University                                                                                         1
El Consejo Nacional de Desarrollo Científico y Tecnológico (CNPq) de Brasil                               1
Universidad Científica del Sur (Perú)                                                                     1
Ministerio de la Igualdad y la Equidad                                                                    1
Wellcome Trust                                                                                            1
Conselho Nacional de Desenvolvimento Científico e Tecnológico - CNPq                                      1
Spencer Foundation                                                                                        1
Universidad Santo Tomas Seccional Tunja                                                                   1
Fundação de Amparo à Pesquisa do Estado de Minas Gerais – FAPEMIG, Brasil                                 1
Name: count, dtype: int64

In [29]:
data['ALIADO'].value_counts()

ALIADO
1- Asociación Colombiana de micros y pequeñas empresas - ACOPI seccional Atlántico\n2- CLI Corporation                                                                                                                                              5
1- Universidad Nacional de Colombia - UNAL                                                                                                                                                                                                          4
1- Universidad Militar Nueva Granada UMNG                                                                                                                                                                                                           3
1- Ejecutor: Corporación Universitaria Minuto de Dios\n2- Aliado: Corporación Centauro Bacata                                                                                                                                                       2
1- Ejecutor:TECSOL\n2- Aliado Institucional: Alcaldía de Guacheta                                                                                                                                                                                   2
                                                                                                                                                                                                                                                   ..
•\tEmpresa Agencia ÁGATA\n•\tRed de Docentes Investigadores REDDI\n                                                                                                                                                                                 1
•\nGrupo De Investigación Y Desarrollo En Tecnologías De La Información Zeety S A S (Empresa Aliada)\n•\nUniversidad Pedagógica y Tecnológica de Colombia (Co-ejecutora)                                                                            1
SINNETIC                                                                                                                                                                                                                                            1
• Universidad de Cundinamarca\n• Universidad Pedagógica y Tecnológica de Colombia UPTC\n• LogOn Colombia SAS\n• Asociación de Productores Agropecuarios de La Calera\n• Asociación Agropecuaria en Unión de la mujer Rural municipio de Silvania    1
INSTITUCIÓN UNIVRSITARIA DEL PUTUMAYO (IES) [antes Instituto Tecnológico del Putumayo], SOFTPROJECT COLOMBIA ZOMAC S.A.S, ASOCIACION DE AFRODESENDIENTES DE SAN JOSE DEL FRAGUA- CAQUETA. AAFROSA,                                                  1
Name: count, Length: 225, dtype: int64

In [30]:
data['PROGRAMA'].value_counts()

PROGRAMA
Pertenence a un programa                                                                                                                                                                                                                  2
Linea 3 Alcance 2                                                                                                                                                                                                                         2
CAPACIDADES COMUNITARIAS EN ZONAS RURALES DE POSACUERDO: OPORTUNIDADES PARA DISMINUIR DESIGUALDADES                                                                                                                                       1
NANOMATERIALES Y DISPOSITIVOS OPTOELECTRÓNICOS                                                                                                                                                                                            1
PROGRAMA DE ENTRENAMIENTO COGNITIVO BASADO EN LA PRÁCTICA DEL AJEDREZ PARA ESTIMULAR LAS FUNCIONES EJECUTIVAS IMPLICADAS EN EL PENSAMIENTO LÓGICO MATEMÁTICO. DIRIGIDO A ESTUDIANTES DEL PRIMER CICLO DE EDUCACIÓN BÁSICA                 1
Configuración de categorías mediante procesos de innovación para la inclusión y el reconocimiento de la diversidad y diferencia cultural en la educación científica: Estudios de caso en los niveles educativos Básico y Universitario    1
Desarrollo y validación de un prototipo de sensor electrofisiológico para medir estrés en plantas.                                                                                                                                        1
106072 - Centro de planeación de microrredes inteligentes                                                                                                                                                                                 1
Programa de Investigación en Tecnologías Emergentes para Microrredes Eléctricas Inteligentes con Alta Penetración\nde Energías Renovables                                                                                                 1
Linea 2 Alcance 1                                                                                                                                                                                                                         1
Linea 3 Alcance 1                                                                                                                                                                                                                         1
Linea 4 Alcance 1                                                                                                                                                                                                                         1
OPTIMIZACIÓN DEL DIAGNÓSTICO Y MANEJO DE LA DIABETES MEDIANTE MODELOS AVANZADOS DE DATOS Y BIOMARCADORES DIGITALES EN MUNICIPIOS DE GUACARÍ - VALLE DEL CAUCA Y HONDA - TOLIMA                                                            1
Name: count, dtype: int64

In [31]:
data['No. CONVOCATORIA'].value_counts()

No. CONVOCATORIA
852                  13
934                  12
37                   12
890                   9
Solución COVID-19     8
                     ..
966                   1
50                    1
03 de 2025            1
44                    1
1                     1
Name: count, Length: 85, dtype: int64

In [69]:
columnas = ['ESTADO', 'ENTIDAD', 'ALIADO', 'ROL UDFJC','AÑO', 'MESES', 'VALOR PROYECTO']
validacion = data[columnas]
validacion.head()

,ESTADO,ENTIDAD,ALIADO,ROL UDFJC,AÑO,MESES,VALOR PROYECTO
0,Contrato firmado,Alcaldía de Fontibón,Alcaldía de Fontibón,Ejecutor,2021,6,440000000.0
1,No Avalada,MinCiencias,1- Universidad Minuto de Dios\n2- Corporación ...,Co-ejecutor,2018,18,547842614.0
2,No Avalada,MinCiencias,1- Universidad Minuto de Dios\n2- Corporación ...,Co-ejecutor,2018,18,507842614.0
3,No Avalada,MinCiencias,Programa ECOSNORD Francia,Ejecutor,2018,36,78000000.0
4,No Avalada,MinCiencias,Programa ECOSNORD Alemania,Ejecutor,2018,24,108915069.0

In [ ]:
çonteo de valores faltantes para el numero de ocnvocatorias

In [39]:
# Los proyectos con diferente estado final tienen diferencias en su valor

data['VALOR PROYECTO'] = data['VALOR PROYECTO'].astype(str).str.replace('$', '', regex=False).str.replace('€', '', regex=False).str.replace('.', '', regex=False).str.replace(',', '.', regex=False).str.replace(' ', '', regex=False).str.replace('-', '', regex=False)
data['VALOR PROYECTO'] = pd.to_numeric(data['VALOR PROYECTO'], errors='coerce')

data.groupby('ESTADO')['VALOR PROYECTO'].agg(['count', 'mean', 'median', 'min', 'max'])

                  count          mean        median          min           max
ESTADO
Avalada              16  7.258009e+09  7.895250e+09  320507100.0  1.200000e+10
Contrato firmado     43  8.770090e+08  4.689722e+08    5675900.0  8.426449e+09
Desistio             18  2.223459e+09  9.259224e+08    9300000.0  8.421200e+09
En tramite           13  1.893340e+11  5.300050e+09   20380900.0  6.847500e+11
No Avalada          163  7.511343e+09  8.978052e+08    5675900.0  4.868489e+10
Seleccionada         22  6.710363e+09  7.519481e+08   40500000.0  4.413614e+10

In [64]:
# crear el data freame

data.groupby(['ENTIDAD', 'ESTADO']).size()

ENTIDAD                                  ESTADO
ATENEA                                   Desistio            1
                                         No Avalada          3
                                         Seleccionada        1
Agencia Nacional del Espectro - ANE      No Avalada          3
Alcaldía de Fontibón                     Contrato firmado    1
                                                            ..
Universidad Santo Tomas Seccional Tunja  Seleccionada        1
Universidad de América                   No Avalada          1
Universidad de Sucre                     Desistio            1
Universidad del Bosque                   Desistio            1
Wellcome Trust                           No Avalada          1
Length: 66, dtype: int64

In [44]:
data[['ENTIDAD', 'ESTADO']].value_counts()

ENTIDAD                                  ESTADO
MinCiencias                              No Avalada          146
                                         Contrato firmado     28
                                         Desistio             13
MinAmbiente (SGR)                        Avalada              12
MinCiencias                              Seleccionada         12
                                                            ...
Universidad Santo Tomas Seccional Tunja  Seleccionada          1
Universidad de América                   No Avalada            1
Universidad de Sucre                     Desistio              1
Universidad del Bosque                   Desistio              1
Wellcome Trust                           No Avalada            1
Name: count, Length: 66, dtype: int64

In [47]:
#El valor promedio de los proyectos cambia dependiendo del estado final

print(data.groupby('ESTADO')['VALOR PROYECTO'].mean())

ESTADO
Avalada             7.258009e+09
Contrato firmado    8.770090e+08
Desistio            2.223459e+09
En tramite          1.893340e+11
No Avalada          7.511343e+09
Seleccionada        6.710363e+09
Name: VALOR PROYECTO, dtype: float64

In [48]:
print(data.groupby('ESTADO')['VALOR PROYECTO'].median())

ESTADO
Avalada             7.895250e+09
Contrato firmado    4.689722e+08
Desistio            9.259224e+08
En tramite          5.300050e+09
No Avalada          8.978052e+08
Seleccionada        7.519481e+08
Name: VALOR PROYECTO, dtype: float64

In [60]:
resultado_aliado = data.groupby(['ALIADO', 'ESTADO']).size()
resultado_programa = data.groupby(['PROGRAMA', 'ESTADO']).size()
resultado_convocatoria = data.groupby(['No. CONVOCATORIA', 'ESTADO']).size()

print (resultado_aliado)
print (resultado_programa)
print (resultado_convocatoria)

ALIADO                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ESTADO
*EFICIENCIA ENERGETICA Y GENERACION ALTERNATIVA DE ENERGIA SAS \n* AGRO360 SAS COEJECUTOR\n* ASOCIACION DE PRODUCTORES AGROPECUARIOS AGUAS VIVAS TOTORO \n* UNIVERSIDAD TECNOLÓGICA DE PEREIRA                                                                                                                                                                                                                                                                                                 En tramite          1
- CORPORACIÓN TECNOLÓGICA INDUSTRIAL COLOMBIANA\n- FUNDACIÓN UNIVERSITARIA\nPANAMERICANA\n- UNIVERSIDAD SANTO TOMAS                                                                                                                                                                                                                                                                                                                                                                            No Avalada          1
- FUNDACIÓN UNIVERSITARIA LOS LIBERTADORES\n- UNIVERSIDAD TECNOLOGICA DEL CHOCO DIEGO LUIS CORDOBA\n- UNIVERSIDAD TECNOLOGICA DEL CHOCO DIEGO LUIS CORDOBA                                                                                                                                                                                                                                                                                                                                     No Avalada          1
- PONTIFICIA UNIVERSIDAD JAVERIANA\n- COLOMBIANA DE TRASPLANTES SAS\n- HOSPITAL MILITAR CENTRAL\n- SOCIEDAD COLOMBIANA DE INGENIERIA\nFISICA\n- UNIVERSIDAD EL BOSQUE                                                                                                                                                                                                                                                                                                                          No Avalada          1
- Universidad Antonio Nariño (co-ejecutora)                                                                                                                                                                                                                                                                                                                                                                                                                                                    Contrato firmado    1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ..
• Resguardo Ancestral Del Pueblo Tamaz Dujos Del Caguán Paniquita\n• Familias del resguardo indígena\n• Departamento del Huila                                                                                                                                                                                                                                                                                                                                                                 Avalada             1
• Resguardo Indígena De Tóez De Caloto - Cooperante\n• Familias del resguardo indígena - Beneficiario\n• Departamento del Cauca - Beneficiario                                                                                                                                                                                                                                                                                                                                                 Avalada             1
• Universidad de Cundinamarca\n• Universidad Pedagógica y Tecnológica de Colombia UPTC\n• LogOn Colombia SAS\n• Asociación de Productores Agropecuarios de La Calera\n• Asociación Agropecuaria en Unión de la mujer Rural municipio de Silvania                                                                                                                                                                                                                                               Avalada             1
• Universidad de Pamplona\n• Universidad Francisco de Paula Santander\n• Gobernación de Santander\n• Municipio de Aguazul, Casanare\n• Municipio de San José de Cucuta, Norte de Santander\n• Asociación Mujer Rural de Cucuta\n• Asociación de agricultores del municipio de Motiscua\n• Asociación de agroindustrial de fruticultores de la Floresta\n• Asociación de asociaciones de productores de Cacao del Norte de Santander y su Región del Catatumbo\n•  Cámara de comercio de Ocaña  No Avalada          1
• Universidad de Pamplona\n• Universidad Francisco de Paula Santander\n• Gobernación de Santander\n• Municipio de Tarqui\n• Municipio de Combita\n• Cooperativa Multiactiva Agropecuaria de Colombia\n• Asociación de productores agropecuarios de Santurban\n• Asociación de mujeres agricultoras Sotaquireñas\n•  Cámara de comercio de Ocaña\n•  Asociacion Colombiana de Micro, Pequeña y Mediana Empresa-ACOPI Regional Noret de Santander                                                No Avalada          1
Length: 228, dtype: int64
PROGRAMA                                                                                                                                                                                                                                ESTADO
106072 - Centro de planeación de microrredes inteligentes                                                                                                                                                                               No Avalada          1
CAPACIDADES COMUNITARIAS EN ZONAS RURALES DE POSACUERDO: OPORTUNIDADES PARA DISMINUIR DESIGUALDADES                                                                                                                                     No Avalada          1
Configuración de categorías mediante procesos de innovación para la inclusión y el reconocimiento de la diversidad y diferencia cultural en la educación científica: Estudios de caso en los niveles educativos Básico y Universitario  No Avalada          1
Desarrollo y validación de un prototipo de sensor electrofisiológico para medir estrés en plantas.                                                                                                                                      Desistio            1
Linea 2 Alcance 1                                                                                                                                                                                                                       No Avalada          1
Linea 3 Alcance 1                                                                                                                                                                                                                       No Avalada          1
Linea 3 Alcance 2                                                                                                                                                                                                                       No Avalada          2
Linea 4 Alcance 1                                                                                                                                                                                                                       No Avalada          1
NANOMATERIALES Y DISPOSITIVOS OPTOELECTRÓNICOS                                                                                                                                                                                          No Avalada          1
OPTIMIZACIÓN DEL DIAGNÓSTICO Y MANEJO DE LA DIABETES MEDIANTE MODELOS AVANZADOS DE DATOS Y BIOMARCADORES DIGITALES EN MUNICIPIOS DE GUACARÍ - VALLE DEL CAUCA Y HONDA - TOLIMA                                                          Seleccionada        1
PROGRAMA DE ENTRENAMIENTO COGNITIVO BASADO EN LA PRÁCTICA DEL AJEDREZ PARA ESTIMULAR LAS FUNCIONES EJECUTIVAS IMPLICADAS EN EL PENSAMIENTO LÓGICO MATEMÁTICO. DIRIGIDO A ESTUDIANTES DEL PRIMER CICLO DE EDUCACIÓN BÁSICA               No Avalada          1
Pertenence a un programa                                                                                                                                                                                                                Contrato firmado    1
                                                                                                                                                                                                                                        No Avalada          1
Programa de Investigación en Tecnologías Emergentes para Microrredes Eléctricas Inteligentes con Alta Penetración\nde Energías Renovables                                                                                               Contrato firmado    1
dtype: int64
No. CONVOCATORIA        ESTADO
03 de 2025              No Avalada      1
1                       Avalada         1
10                      Avalada         3
                        No Avalada      1
1047                    No Avalada      3
                                       ..
No es una convocatoria  No Avalada      1
PR3                     En tramite      1
                        Seleccionada    2
Solución COVID-19       No Avalada      8
VIII UNIMINUTO          No Avalada      1
Length: 110, dtype: int64

In [61]:
conteo = data.groupby(['ENTIDAD', 'ESTADO']).size()
total = data.groupby('ENTIDAD').size()
porcentaje = (conteo / total) * 100
print(porcentaje)

ENTIDAD                                  ESTADO
ATENEA                                   Desistio             20.0
                                         No Avalada           60.0
                                         Seleccionada         20.0
Agencia Nacional del Espectro - ANE      No Avalada          100.0
Alcaldía de Fontibón                     Contrato firmado    100.0
                                                             ...
Universidad Santo Tomas Seccional Tunja  Seleccionada        100.0
Universidad de América                   No Avalada          100.0
Universidad de Sucre                     Desistio            100.0
Universidad del Bosque                   Desistio            100.0
Wellcome Trust                           No Avalada          100.0
Length: 66, dtype: float64

cual sera la variable para ver el histograma y la variable de cajas

In [70]:
Nuestro análisis estadístico

1. Para VALOR PROYECTO

Estadística descriptiva: media, mediana, mínimo, máximo.
Histograma.
Boxplot por ESTADO.
ANOVA para comprobar si existen diferencias entre los tres estados.
Si no se cumplen los supuestos de ANOVA → Kruskal-Wallis.

2. Para ENTIDAD, ALIADO, PROGRAMA y No. CONVOCATORIA

Frecuencias.
Porcentajes.
Tablas cruzadas mediante groupby() o value_counts().
Chi-cuadrado para comprobar si existe asociación con ESTADO.

SyntaxError: invalid character '→' (U+2192) (1698339941.py, line 9)

In [ ]:
darle péso a min ciencias con  bool